trigger:
  branches:
    include:
      - main   # run pipeline whenever main changes

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self

  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'  # or your runtime version
    displayName: 'Setup Node.js'

  - script: npm install
    displayName: 'Install dependencies'

  - script: npm run build
    displayName: 'Build app'


